services:
  - type: web
    name: laravel-app
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://Fleet_Services.com
      - key: APP_KEY
        sync: false   # Render va en générer un automatiquement
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: 127.0.0.1
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: eneo_fleet_services
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        sync: false

