services:
  - type: web
    name: laravel-app
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://fleet-services.onrender.com
      - key: APP_KEY
        sync: base64:eoGKNzIeQHi0DXAnoukrTR7tFTQfnylc/zSKdmWUaiY=
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: mysql-3d31e0b0-komguepnelly55-6ad2.l.aivencloud.com
      - key: DB_PORT
        value: 14467
      - key: DB_DATABASE
        value: defaultdb
      - key: DB_USERNAME
        value: avnadmin
      - key: DB_PASSWORD
        sync: AVNS_FTP4iHycWkpn1Hdh9Ev
    postDeployCommand: |
      php artisan config:clear &&
      php artisan cache:clear &&
      php artisan route:clear &&
      php artisan view:clear

