services:
  - type: web
    name: laravel-app
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: true
      - key: APP_URL
        value: https://eneo-fleet-services.onrender.com
      - key: APP_KEY
        sync: base64:eoGKNzIeQHi0DXAnoukrTR7tFTQfnylc/zSKdmWUaiY=
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d30gmgp5pdvs7380c3m0-a
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: eneo_fleet_services
      - key: DB_USERNAME
        value: eneo_fleet_services_user
      - key: DB_PASSWORD
        sync: GWQpD5MeJRKgO490YGiGKfVZVqrLdKcV

